[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
/(
    \.venv
  | build
  | dist
  | \.git
  | \.tox
  | data/tennis_atp/examples.*
)/
'''

[tool.ruff]
src = ["src"]
exclude = [
  "build",
  "dist",
  ".venv",
  "data/tennis_atp/examples"
]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501"]  # Let Black handle line length

[tool.isort]
profile = "black"
skip = [
    "build",
    "dist",
    ".venv",
    "data/tennis_atp/examples"
]
