[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
/(
    \.venv
  | build
  | dist
  | \.git
  | \.tox
  | data/tennis_atp/examples.*
)/
'''

[tool.ruff]
src = ["src"]
exclude = [
  "build",
  "dist",
  ".venv",
  "data/tennis_atp/examples"
]

[tool.ruff.lint]
# E (pycodestyle), F (Pyflakes), I (isort)
select = ["E", "F", "I"]
ignore = ["E501"]  # Let Black handle line length
