defaults:
  tour: ATP
  year: 2023

tournaments:
  - label: ausopen_2023_atp
    tour: ATP
    tournament: ausopen
    year: 2023
  - label: rolandgarros_2023_atp
    tour: ATP
    tournament: rolandgarros
    year: 2023
  - label: wimbledon_2023_atp
    tour: ATP
    tournament: wimbledon
    year: 2023
