name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 black

    - name: Lint with flake8
      run: |
        flake8 src scripts tests

    - name: Check formatting with black
      run: |
        black --check .

    - name: Run tests
      run: |
        pytest -v

    - name: Smoke-test pipeline (dry-run)
      run: |
        python src/scripts/pipeline/run_full_pipeline.py \
          --config configs/pipeline_run.yaml \
          --batch \
          --dry_run
