name: Python CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'        # adjust as needed
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt         # core deps (includes python-json-logger) :contentReference[oaicite:0]{index=0}
          pip install pytest pytest-cov flake8 ruff mypy

      - name: Lint with Black
        run: black --check src scripts

      - name: Lint with Ruff
        run: ruff check src scripts

      - name: Type-check with MyPy
        run: mypy src scripts

      - name: Run tests
        run: |
          PYTHONPATH=src pytest --maxfail=1 --disable-warnings -q

      - name: Test coverage report
        run: pytest --cov=src --cov-report=term-missing
