name: Python CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Use 3.13 if that's what you want for consistency

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check code formatting (Black)
      run: |
        pip install black
        black --check .

    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check .

    - name: Run all tests
      run: PYTHONPATH=src pytest -v

    - name: Test coverage report
      run: |
        pip install pytest-cov
        PYTHONPATH=src pytest --cov=src --cov-report=term-missing
