name: Python CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  # Use your local Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run all tests
      run: PYTHONPATH=src pytest -v

    - name: Test coverage report
      run: |
        pip install pytest-cov
        PYTHONPATH=src pytest --cov=src --cov-report=term-missing

